add voms-api-java and trustmanager from /usr/share/java in classpath

diff --git a/src/main/scripts/sbin/pepdctl b/src/main/scripts/sbin/pepdctl
--- a/src/main/scripts/sbin/pepdctl
+++ b/src/main/scripts/sbin/pepdctl
@@ -40,8 +40,19 @@ if [ ! -x "$JAVACMD" ] ; then
     exit 1
 fi
 
+# add voms-api-java and trustmanager from /usr/share/java in classpath
+USR_SHARE_JAVA="/usr/share/java"
+if [ ! -f "$USR_SHARE_JAVA/vomsjapi.jar" ] ; then
+    echo "$0: ERROR: $USR_SHARE_JAVA/vomsjapi.jar not found, VOMS Java API package not installed"
+    exit 1
+fi
+if [ ! -f "$USR_SHARE_JAVA/trustmanager.jar" ] ; then
+    echo "$0: ERROR: $USR_SHARE_JAVA/trustmanager.jar not found, EMI Trustmanager package not installed"
+    exit 1
+fi
+LOCALCLASSPATH="$USR_SHARE_JAVA/vomsjapi.jar:$USR_SHARE_JAVA/trustmanager.jar"
 
-# add in the dependency .jar files from the lib directory
+# add in the dependency .jar files from the pepd lib directory
 jarfiles="$PEPD_LIBDIR/*.jar"
 for jar in $jarfiles
 do
